name: Publish to NPM
on: 
  push:
    branches: master

jobs:
  build:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wuz/publish-to-npm@master
        with:
          npm-token: ${{ secrets.npmToken }}
